# -*- coding: utf-8 -*-
"""ProjEulerProb9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hOhHUBfJ2MAiOqo2R6qn34UTa7ohcbdu
"""

for a in range(3, 1000):
    for b in range (a + 1, 999):
        csquared = a**2 + b**2
        c = cSquared**0.5

        if a + b + c == 1000:
            product = a * b * c
print(product)

