# -*- coding: utf-8 -*-
"""ProjEulerProb5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ag46ZdFUa5_R1Emeb_dTIkBuSMhdMQch
"""

def gcd(a,b): return b and gcd(b, a % b) or a
def lcm(a,b): return a * b / gcd(a,b)

n = 1
for i in range(1, 21):
    n = lcm(n, i)

print (n)