# -*- coding: utf-8 -*-
"""ProjEulerProb6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Kpjng-zogaiGOL0eTazxB8t7Y8K_vjPs
"""

r = range(1, 101)
a = sum(r)
print (a * a - sum(i*i for i in r))