# -*- coding: utf-8 -*-
"""ProjEulerProb7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ruyFxnn3HE0AYS5jsmRRooCOiD1zVcGa
"""

def isPrime(n):
    if n < 2: return "Neither prime, nor composite"
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# returns the nth prime number
def nthPrime(n):
    numberOfPrimes = 0
    prime = 1

    while numberOfPrimes < n:
        prime += 1
        if isPrime(prime):
            numberOfPrimes += 1
    return prime

print(nthPrime(10001))