# -*- coding: utf-8 -*-
"""ProjEulerProb1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LkR2TH-QzWpgAp9hsCv9fo-YhTthRw73
"""

#Import numpy
import numpy as np
#
# Build the list (note that the problem states "below" 1000,
# so we can safely use 1000 rather than 1001 in range)
multiples_of_three_and_five = [number for number in range(1,1000) if number % 3 == 0 or number % 5 == 0]

#Sum the list
np.sum(multiples_of_three_and_five)

# We can also accomplish the sum with a loop if you'd like to avoid using numpy sum function:

# Initialize a dummy variable at zero to hold our result
sum_of_multiples = 0

# Loop over our list, adding each number in the list to sum_of_multiples
for number in multiples_of_three_and_five:
  sum_of_multiples += number

sum_of_multiples

# Without the list comprehension; see if you can spot the difference in results:
sum_multiples = 0
for num in range(1000):
    if num % 3 == 0 or num % 5 == 0:
        sum_multiples += num

sum_multiples