# -*- coding: utf-8 -*-
"""ProjEulerProb15

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uCmUUIdIq3u2uYK0ge7o5H8Oq9HBz0Kq
"""

def fact(n):
    f = 1
    for x in range(1, n+1): f = f * x
    return f

print (fact(40) / fact(20) / fact(20))